[book]
title = "The Nightmare Guide to Game Programming"
authors = ["Christian Viñolo"]
multilingual = true
src = "src"

[output.html]
preferred-dark-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
